# NumPy Nedir? 
Açık kaynaklı kodlu özgür bir python kütüphanesidir
Numerical Python anlamına gelir. Sayılarla daha hızlı matematik işlemler yapmamızı sağlar. 
Numpy kütüphanesinin en temel elemanı array(dizi)dir.
Arrayleri Python dizilerin çok boyutlu olanı gibidir.
Arrayler listelerden yaklaşık 50 kat hızlı çalışır.
Numpy arraylerinin hızlı çalışmasının sebebi bu kütüphanein büyük oranda c ve c++ ile yazılmış olmasıdır.

# NumPy arrayleri oluşturma
Arrayler çok boyutlu diziler gibi düşünülebilir.
Arrayleri üç farklı şekilde oluşturabiliriz.
    
    1-Liste ya da tuple benzeri nesneleri arraye döndürebiliriz. --> np.array([1,2,3])

    2-Built-in hazır fonksiyonlar yardımıyla arrayler oluşturabiliriz. --> np.arange(), np.linspace(), np.logspace() vb.

    3-Rastgele data üreterek --> np.random içerisindeki fonklar yardımıyla

In [ ]:
import numpy as np
arr0d = np.array(53)
arr1d = np.array([1,2,3,4])
arr2d = np.array([[1,2,3], [4,5,6]])
print(arr0d)
arr1d
arr2d
#Built-in Functionlarla Hızlıca Arrayleri Oluşturma
#np.arange() fonksiyonu ile hızlıca istediğimiz sayı aralığında ardışık artan arrayler oluşturabiliriz.
#Kullanımı range() gibi. Start point dahil, End point dahil değil.(start-stop-step parametrelerini alır.)
print(np.array([1,2,3,4,5,6,7,8,9]))
print(np.arange(1,10))
print(np.arange(30,100,2))

# np.linspace() fonk ile de hızlıca arrayler oluşturabiliriz
np.linspace(30,50,6) #endpoint burada dahil

np.logspace(1,3,10) #10 ile 1000 arasında logaritmik artan 10 tane veriden oluşanarray oluşturdu.

#SORU: 10,15,20,25...100 şeklindeki arrayi oluştur
np.arange(10,101,5)
#SORU: 0-1000 arasında eşit aralıklarla ilerleyen 26 tane sayı oluşturun
np.linspace(0,1000,26)

np.zeros(5, dtype='int')  #sıfırlardan oluşan array oluşturur
np.zeros((2,3), dtype=int)
np.ones(10, dtype=int)    #birlerden oluşan array oluşturur
np.ones((2,3), dtype=int)
np.eye(5, dtype=int)      #birim matris 

#SORU: Sadece 0 değerlerindenoluşam (2,6) formatında array oluşturun.
np.zeros((2,6), dtype=int)

### np.random modülü kullanarak rastgele verilerle arrayler oluşturmak
# np.random.fonksiyon - npdeki random modülünden hangi fonk çağırmak isteriz
np.random.rand(3) #0 ile 1 arasındaki değerlerden oluşan bir array oluşturur.
np.random.rand(2,5)
# np.random.rand(3) * 10 dersek 0 ile 10 arasından değerler oluşturur ama önerilmez
# np.random.randint(low, high, size) 
np.random.randint(15,50,5)
np.random.randint(0,100,(3,6))

# SORU: 0ile 50 arasında rastgele sayılardan oluşan 4-6 formatında 24 tane sayıdan oluşan bir array oluşturun.
np.random.randint(0,50,(4,6))

53
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76
 78 80 82 84 86 88 90 92 94 96 98]


array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
#Arrayin Boyut Sayısını ve Shape'i Kontrol Etmek 
# .ndim attribute'ı ile arrayimizin kaç boyutlu olduğuna bakabiliriz.
arr0d.ndim
arr1d.ndim
arr2d.ndim
arr2d.shape  #arrayin shapeine bakılır

#NumPY Arraylerini İndeksleme ve Öğelerine Erişme 
arr1d #1 boyutlu arrayler aynı listeler gibi düşünülebilir 
arr2d[0] #0. satırı verir 
arr2d[0][1]
arr3d = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [100,200,300]]])
arr3d.ndim      #  |     0. kısım  |  |          1.kısım     |
arr3d[0][1][2]  #arr3d[0,1,2] şeklinde de yazılabilir. negatif indeksleme de yapılabilir

#SORU: 53den 61e kadar (ikisi dahil) olan tam sayıları içeren bir array oluşturun. ardından 4. i ndeksteki sayıyı ekrana bastırın 
listm = np.arange(53,62)
listm[4]

#NumPy Dizilerinin Max ve Min Elemanlarına ve Bu Elemanların İndexlerine Erişme 
arr = np.random.randint(1,100,10)
arr.max()
arr.argmax()
arr.min()
arr.argmin()

#NumPy Arraylerinde Slicing (dilimleme) yapılabilir.
arr = np.arange(50,65)
arr
#55 ile 60 arasını çekelim 5 ile10 insexlere kadar al 
arr[5:11]
arr[-5:]
arr[2:10:2] #2şer atlayarak alır 
arr[5:11] = 999 #Broadcasting -belirli aralığı kesip baska bir değere eşitleme
arr            
arr[5:11]
# SORU: -30 ile 10 (ikisi dahil) arasındaki tam sayılardan oluşan bir array oluşturun ardından slicing yaparak
#5. ve 18. indexler arasındaki sayılardan (ikisi dahil) oluşan bi array oluşturun
arr = np.arange(-30,11) 
arr[5:19]

#Bir Arrayin Veri Türünü(Data Type'ını) kontrol etmek 
# .dtype attribute ı ile arrayimizin data type ı kontrol edilebilir.
arr.dtype
arr2 = np.arange(100, dtype = 'float') 
arr2.dtype
arr3 = np.array(['a', 'b', 'c'])
arr3  

#Bir arrayin dtypeını değiştirme 
# .astype() metodu ile arraylerin dtype'ı değiştirilebilir.
arr = np.array([1.2, 3.5, 5.8])
arr.dtype 
arr.astype('int')

#SORU: şeklindeki arrayn typenı inte döndür dtype kontrol et 
arr = np.array(['5','7', '4'])
arr.dtype 
arr.astype('int')
arr #gerçek arr inte dönmedi 
arr = arr.astype(int)
arr 
arr.dtype



dtype('int64')