In [3]:
import numpy as np
# Bir arrayın Shapeini kontrol etmek için .shape attribute u kullanılır
# Bir arrayin shapei her boyuttaki öğelerinin sayısına eşittir

arr2d = np.array([[1,2,3], [4,5,6], [10,20,30]])
arr2d.shape #(3, 3)

(3, 3)

In [4]:
arr3d = np.array([[[1,2,3],[4,5,6], [10,25,35], [40,50,60]], [[10,20,30], [5,10,20],[11,22,33],[44,55,66]]])
arr3d 
arr3d.shape #2boyutlulardan 2 tane var(2, , ), her boyutta 4 satır 3 sütun(2,4,3) 

(2, 4, 3)

**Bir Array'i Reshape (Yeniden Şekillendirme) Etme:**         
.reshape() metodu arrayin şeklini değiştirmeye yarar.                       
.reshape() yaparken toplam eleman sayısını sabit tutmaya dikkat edilmeli.


In [5]:
arr3d
print(arr3d.shape) #(2, 4, 3) 24 eleman var. eleman sayısı değişirse hata verir
arr2d = arr3d.reshape(2,12) 
arr2d

(2, 4, 3)


array([[ 1,  2,  3,  4,  5,  6, 10, 25, 35, 40, 50, 60],
       [10, 20, 30,  5, 10, 20, 11, 22, 33, 44, 55, 66]])

In [6]:
#Bilinmeyen Boyut
# .reshape() methodu kullanılırken hesaplamak istemediğimiz boyut yerine-1 yazıp otomatik hesaplattırabiliriz 
arr3d = np.arange(120).reshape(5,2,-1) #5*2*? = 120 -1 ile ? bulmakla uğraşmadık 12 boyut oldugunu kendi buldu
arr3d

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23]],

       [[ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47]],

       [[ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71]],

       [[ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95]],

       [[ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]]])

In [7]:
#SORU: 0-59 59dahil arasındakş tam sayılardan oluşan bşr array oluşturun.
#Bu arrayin shapesini değiştirerek istediğiniz shapelerde 3 boyutlu bir array elde edin.
arr = np.arange(60).reshape(2,3,-1)
print(arr.shape)
arr


(2, 3, 10)


array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]])

**Arrayleri Düzleştirme(Flatten):**  
Düzleştirme işlemi(flatten) çok boyutlu bir arrayi 1 boyutlu hale döndürmeye denir.    
Basitçe .reshape(-1) metoduyla yapılır

In [8]:
arr2d = np.arange(40).reshape(8,5)
print(arr2d.shape)
print(arr2d)

arr = arr2d.reshape(-1)
arr


(8, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [9]:
#SORU: 30 elemanlı 3 boyutlu bir array oluştur ve düzleştirin boyutunu, shapeimi kontrol edin
arr = np.arange(30).reshape(2,5,-1)
print(arr.ndim)
print(arr.shape)
arr.reshape(-1)

3
(2, 5, 3)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

**Çok Boyutlu Arraylerde Iteration(Yenileme)**

In [10]:
arr1d = np.arange(10)
arr1d 
for x in arr1d:
    print(x)
    

0
1
2
3
4
5
6
7
8
9


In [11]:
arr2d = np.arange(20).reshape(4,5)
print(arr2d)
print('-------------------')
for x in arr2d:
    print(x) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
-------------------
[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [12]:
for x in arr2d:
    for y in x:
        print(y)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [13]:
arr3d = np.arange(30).reshape(-1,3,5)
arr3d 


array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

**Çok Boyutlu Arraylerde nditer() Kullanımı**  
For döngüsü arrayin boyutu kadar sayıda kullanılırsa arrayin bütün elemanlarına tek tek erişebiliriz.  
Çok boyutlu arraylerde nditer() fonku bunun için geliştirilmiştir.  
For döngüsünden .çok daha efektif ve hızlı bir şekilde tüm elemanları dönmemizi sağlar.  


In [14]:
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [15]:
for x in np.nditer(arr3d):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


In [16]:
#SORU: 0-119dahil toplam 120 elemanlı bir array oluşturun ve arrayin shapeni ayarlayarak 3 boyutlu hale getirin
# devamında da içindeki tüm elemanları tek tek dönün
arr = np.arange(120).reshape(5,2,-1)
for x in np.nditer(arr):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119


In [17]:
# Array Elemanları Arasında 4 İşlem
arr1 = np.array([10,20,50,100])
arr2 = np.array([5,7,9,-1])
print(arr1 + arr2)
print(arr1.__add__(arr2))
print(arr1 - arr2)
print(arr1.__sub__(arr2))
arr1*arr2
arr1/arr2
arr1//arr2

[15 27 59 99]
[15 27 59 99]
[  5  13  41 101]
[  5  13  41 101]


array([   2,    2,    5, -100])

**Bir Arrayin Toplamına/Ortalamasına/Varyansına/Standart Sapmasına Bakma**

In [18]:
arr = np.random.randint(0,10, 10)
arr

array([7, 2, 2, 5, 1, 0, 8, 0, 1, 5], dtype=int32)

In [19]:
arr.sum()

np.int64(31)

In [20]:
arr.mean() #ortalama 

np.float64(3.1)

In [21]:
arr.var() #bir veri kümesindeki farkın ne kadar büyük olduğunun istatistiksel bir ölçüsüdür.

np.float64(7.69)

In [22]:
arr.std() #varyansın karekökü 

np.float64(2.7730849247724096)

In [23]:
np.sqrt(arr) #ayrı kareköklerini alır 

array([2.64575131, 1.41421356, 1.41421356, 2.23606798, 1.        ,
       0.        , 2.82842712, 0.        , 1.        , 2.23606798])

In [24]:
np.sin(arr) 

array([ 0.6569866 ,  0.90929743,  0.90929743, -0.95892427,  0.84147098,
        0.        ,  0.98935825,  0.        ,  0.84147098, -0.95892427])

In [25]:
#SORU: 0-100 arası rastgele 10 tam sayıdan olusan arrayın üstteki değerlerini bul
arr2 = np.random.randint(0,100,10)
print(arr2)
print(arr2.sum())
print(arr2.mean())
print(arr2.max())
print(arr2.var())
print(arr2.std())




[55 16 23 95 41 17 18  4 73 14]
356
35.6
95
799.6400000000001
28.277906570324475


**Numpy Arraylerini Birleştirme (Concatanate)**  
Numpy arraylerini birleştirme işlemi .contaneate() fonk ile yapılır. Fonksiyonun içine liste halinde birleştirilecek arrayler verilir.  
np.concatenate([arr1,arr2], axis = 1)

In [31]:
arr1 = np.array([10,20,30,70])
arr2 = np.array([100,200,600,900])
np.concatenate([arr1,arr2] , axis = 0) #axis 0 satır halinde yan yana birleştirir.
# np.concatenate([arr1,arr2], axis = 1)  hata çünkü axis = 1 diye bir eksen yok tek boyurlu dizilerle yapmaya çalıştığım için hata verdi


array([ 10,  20,  30,  70, 100, 200, 600, 900])

In [34]:
# eğer sütun bazlı birleştirme yapmak istiyorsak reshape ile boyut değiştirebiliriz 
arr1 = arr1.reshape(4, 1)
arr2 = arr2.reshape(4, 1)
np.concatenate([arr1, arr2], axis = 1)
# np.concatenate([arr1, arr2], axis = 0)


array([[ 10, 100],
       [ 20, 200],
       [ 30, 600],
       [ 70, 900]])

**Arrayleri Stackleme(Yığınlama) İşlemleri**  
Concatenate işlemiyle benzerdir. farklı olarak yeni bir boyut(eksen) üzerinde yığınlamalar yapmasıdır.

In [ ]:
np.concatenate([arr1, arr2], axis = 1)
np.stack([arr1, arr2], axis = 0)#yeni bir ek boyut ekleyerek yığınlamayı yapar.

array([[[ 10],
        [ 20],
        [ 30],
        [ 70]],

       [[100],
        [200],
        [600],
        [900]]])

In [38]:
# np.hstack() -> satır boyunca yığınlama
# np.vstack() -> sütun boyunca yığınlama 

**NumPy Arraylerinde Arama**  
Aradığımız değerlerin bulunduğu indexleri döndürmek için np.where() fonk kullanırız.  
np.where() içerisine argüman olarak condition(şart) alır.

In [39]:
arr = np.array([1,2,5,6,7,7,9,2,2,2])
arr

array([1, 2, 5, 6, 7, 7, 9, 2, 2, 2])

In [41]:
np.where(arr==9) #arrain kaçıncı indexlerinde 9 oldugunu söyler 

(array([6]),)

In [42]:
np.where(arr==2)

(array([1, 7, 8, 9]),)

In [43]:
np.where(arr%2 != 0) #tek elemanların indexlerini çekmiş olduk.

(array([0, 2, 4, 5, 6]),)

**NumPy'da Random Kütüphanesi**  
Random diye ayrı bir kütüphane olmasının yanı sıra Numpy kütüphanesinin içinde random adında bir modül de bulunur.  
Numpyıın içindeki random modülü normal random kütüphanesinden daha kapsamlıdır.

In [47]:
# form numpy import random şeklinde alablriz ama gerek yok 
import numpy as np 
np.random.rand() #0-1 arası rastgele sayı döndürür.

0.8814252203212621

In [49]:
np.random.randn(5) #rastgele normal dağılımlı sayı üretir. #sadece standart normal dağılım üretir.  
# np.random.randn(n), standart normal dağılımdan (ortalama 0, standart sapma 1) n tane rastgele sayı üretir.

array([-2.23399303,  0.23345325, -0.93728538, -0.12372645,  0.58029143])

In [48]:
np.random.randint(low = 10, high = 30,size = 5)

array([19, 19, 28, 12, 25], dtype=int32)

In [54]:
arr

array([1, 2, 5, 6, 7, 7, 9, 2, 2, 2])

In [55]:
np.random.choice(arr) #diziden rastgele sayı çeker.

np.int64(5)

In [ ]:
np.random.choice([3,-1,15]) #bu sayılardan rastgele birini döndürür

np.int64(3)