# DateFrame Basics

**-DF Oluşturma**  
**-DF'in içerisinde bir ya da birden falza coulmn(sütunu) seçmek.**  
**-DF'in içerisinde bir ya da birden fazla row'u(satırı) seçmek.**  
**-DF'in içerisine bir coulmn ya da row ekleme.**  

In [6]:
import numpy as np
import pandas as pd
#Bir DateFrame nasıl oluşur? içeriisnde bir coulmn(başlıklar) var indexler var(zorunlu değiller) bir de veriler var
# pd.DataFrame() fonksiyonuyla basitçe df oluşturabiliriz.

In [7]:
my_data = np.random.randint(0, 101, size=(5,4)) #5,4 satır,sütun
print(my_data)
pd.DataFrame(my_data)


[[13 72 19  9]
 [49 49 54 21]
 [75 67 70 11]
 [ 5 47 13 28]
 [71  5 39 13]]


0   1   2   3
0  13  72  19   9
1  49  49  54  21
2  75  67  70  11
3   5  47  13  28
4  71   5  39  13

In [11]:
#belirlediğimiz row coulmn ve veriler ile df oluşturma
my_index = ['TR', 'BR', 'USA','RU']
my_cols = ['Jan', 'Feb', 'Mar']
my_data = np.random.randint(0,101, size=(4,3))
print(my_data)
df = pd.DataFrame(data = my_data, index = my_index, columns = my_cols)
df

[[84 57 71]
 [87 65 54]
 [73  3 90]
 [91 58 95]]


Jan  Feb  Mar
TR    84   57   71
BR    87   65   54
USA   73    3   90
RU    91   58   95

In [12]:
df.info() #info() metodu ile DFin içindeki bütün columnların temel bilgilerini göebiliriz

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, TR to RU
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int32
 1   Feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes


**Hazır Bir Data Çağırmak**

In [5]:
pwd

'c:\\Users\\sudem\\Desktop\\Yeni klasör\\pandas'

In [3]:
#.csv ya da .xlsx vb. dosya formatlarını df olarak okuyabiliriz.  
#.csv dosya formatını okumak için pd.read_csv() fonksiyonunu kullanırız.
# pd.read_csv("tips.csv") #eğer aynı klasör içeriisne aldıysak sadece adını yazmak yeterli. dosya yolunu yazarız parantez içine 
dosya_yolu = r'C:\Users\sudem\Desktop\Yeni klasör\pandas\tips.csv'
df = pd.read_csv(dosya_yolu)
df

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[244 rows x 11 columns]

In [4]:
df.head() #ilk beşini verir
df.head(3)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458

In [44]:
df.tail()

total_bill   tip     sex smoker   day    time  size  price_per_person  \
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

          Payer Name         CC Number Payment ID  
239    Michael Avila  5296068606052842    Sat2657  
240   Monica Sanders  3506806155565404    Sat1766  
241       Keith Wong  6011891618747196    Sat3880  
242     Dennis Dixon     4375220550950      Sat17  
243  Michelle Hardin  3511451626698139    Thur672

In [46]:
df.sample() #karışık örnek verir kaç tane istersen. yazmazsan bir tane
df.sample(4)

total_bill   tip     sex smoker  day    time  size  price_per_person  \
94        22.75  3.25  Female     No  Fri  Dinner     2             11.38   
59        48.27  6.73    Male     No  Sat  Dinner     4             12.07   
238       35.83  4.67  Female     No  Sat  Dinner     3             11.94   
36        16.31  2.00    Male     No  Sat  Dinner     3              5.44   

         Payer Name         CC Number Payment ID  
94      Jamie Garza      676318332068    Fri2318  
59      Brian Ortiz  6596453823950595    Sat8139  
238  Kimberly Crane      676184013727    Sat9777  
36     William Ford  3527691170179398    Sat9139

In [ ]:
df.shape #kaç satır kaç sütün oldugunu tuple olarak görebiliyoruz.

(244, 11)

In [ ]:
df.columns #Columnslarımızın isimlerini liste halinde görebiliyoruz

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [ ]:
df.info() #her coulmn hakkında bilgi verir, Columnların infosuna bakabiliyoruz.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object 
 3   smoker            244 non-null    object 
 4   day               244 non-null    object 
 5   time              244 non-null    object 
 6   size              244 non-null    int64  
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object 
 9   CC Number         244 non-null    int64  
 10  Payment ID        244 non-null    object 
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB


In [8]:
df.describe() #numeric columnların istatistiksel özetini verir 

total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [ ]:
df.describe().T #T-transpoz

count          mean           std           min  \
total_bill        244.0  1.978594e+01  8.902412e+00  3.070000e+00   
tip               244.0  2.998279e+00  1.383638e+00  1.000000e+00   
size              244.0  2.569672e+00  9.510998e-01  1.000000e+00   
price_per_person  244.0  7.888197e+00  2.914234e+00  2.880000e+00   
CC Number         244.0  2.563496e+15  2.369340e+15  6.040679e+10   

                           25%           50%           75%           max  
total_bill        1.334750e+01  1.779500e+01  2.412750e+01  5.081000e+01  
tip               2.000000e+00  2.900000e+00  3.562500e+00  1.000000e+01  
size              2.000000e+00  2.000000e+00  3.000000e+00  6.000000e+00  
price_per_person  5.800000e+00  7.255000e+00  9.390000e+00  2.027000e+01  
CC Number         3.040731e+13  3.525318e+15  4.553675e+15  6.596454e+15

# Column(Sütun) İşlemleri

In [ ]:
#sütun çekmek #seri olarak çektik df için?
df['price_per_person']


0       8.49
1       3.45
2       7.00
3      11.84
4       6.15
       ...  
239     9.68
240    13.59
241    11.34
242     8.91
243     9.39
Name: price_per_person, Length: 244, dtype: float64

In [ ]:
df[['price_per_person']]  #dataframe olarak çektik 
df.price_per_person #bu şekilde de çağırabiliriz ama önermem şimdilik dedi

0       8.49
1       3.45
2       7.00
3      11.84
4       6.15
       ...  
239     9.68
240    13.59
241    11.34
242     8.91
243     9.39
Name: price_per_person, Length: 244, dtype: float64

In [8]:
df[['Payer Name']] #boşluk olunca üstteki 2.kullanım çalışmıyor
df.Payer Name

SyntaxError: invalid syntax (322496151.py, line 2)

In [12]:
df[['sex', 'tip', 'price_per_person']]

sex   tip  price_per_person
0    Female  1.01              8.49
1      Male  1.66              3.45
2      Male  3.50              7.00
3      Male  3.31             11.84
4    Female  3.61              6.15
..      ...   ...               ...
239    Male  5.92              9.68
240  Female  2.00             13.59
241    Male  2.00             11.34
242    Male  1.75              8.91
243  Female  3.00              9.39

[244 rows x 3 columns]

In [ ]:
#AMAÇ: İnsanların bonkörlük düzeylerini hesaplayın.
#NOT: Bonkrlük düzeyi verilen bahsis/ödenen toplam ücret *100 şeklinde hesaplayalım.
print(df.head())
#tüm columnlarla nasıl yaparız- buna vektörize işlemler denir 
df['tip'] / df['total_bill'] * 100

   total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number  
0  Christy Cunningham  3560325168603410  
1      Douglas Tucker  4478071379779230  
2      Travis Walters  6011812112971322  
3    Nathaniel Harris  4676137647685994  
4        Tonya Carter  4832732618637221  


0       5.944673
1      16.054159
2      16.658734
3      13.978041
4      14.680765
         ...    
239    20.392697
240     7.358352
241     8.822232
242     9.820426
243    15.974441
Length: 244, dtype: float64

In [15]:
#bulduğumuz sonucu yeni bir cloumn olarak ekleyelim
df['Bonkörlük_yüzdesi'] = df['tip'] / df['total_bill'] * 100

In [28]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

**Column Düşürme**  
axis belirtilmezse satırlarda arar(axis=0)  
axis=1 sütundan siler  
inplace=True ile kalıcı hale getiririz.

In [29]:
df.drop('Payment ID', axis=1, inplace=True)  

In [30]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number  
0  Christy Cunningham  3560325168603410  
1      Douglas Tucker  4478071379779230  
2      Travis Walters  6011812112971322  
3    Nathaniel Harris  4676137647685994  
4        Tonya Carter  4832732618637221

In [ ]:
#SORU: dfin içeriisnde 	day columnunu ve payer name columnunu düşürün ama kalıcı hale getirmeyin.
df.drop(['day', 'Payer Name'], axis=1)

total_bill   tip     sex smoker    time  size  price_per_person  \
0         16.99  1.01  Female     No  Dinner     2              8.49   
1         10.34  1.66    Male     No  Dinner     3              3.45   
2         21.01  3.50    Male     No  Dinner     3              7.00   
3         23.68  3.31    Male     No  Dinner     2             11.84   
4         24.59  3.61  Female     No  Dinner     4              6.15   
..          ...   ...     ...    ...     ...   ...               ...   
239       29.03  5.92    Male     No  Dinner     3              9.68   
240       27.18  2.00  Female    Yes  Dinner     2             13.59   
241       22.67  2.00    Male    Yes  Dinner     2             11.34   
242       17.82  1.75    Male     No  Dinner     2              8.91   
243       18.78  3.00  Female     No  Dinner     2              9.39   

            CC Number  
0    3560325168603410  
1    4478071379779230  
2    6011812112971322  
3    4676137647685994  
4    4832732618637221  
..                ...  
239  5296068606052842  
240  3506806155565404  
241  6011891618747196  
242     4375220550950  
243  3511451626698139  

[244 rows x 8 columns]

# Row(Satır) İşlemleri  
Satır çekme işlemi .loc ve .iloc metodları ile yapılır.  
.loc - location direkt onu verir. direkt satır ismiyle bilgileri alır  
.iloc ise sayısal olarak yerini verir. satır indexiyle bilgileri alır

In [59]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

In [60]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [61]:
#öncelikle payer name i satır isimleri yapıyoruz o halde payer name sütununa ihtiyacımız da kalmayacak 
df.set_index('Payer Name', drop = True, inplace=True ) #index yap sütundan düşür ve kalıcı yap

In [62]:
df.head(3)

total_bill   tip     sex smoker  day    time  size  \
Payer Name                                                               
Christy Cunningham       16.99  1.01  Female     No  Sun  Dinner     2   
Douglas Tucker           10.34  1.66    Male     No  Sun  Dinner     3   
Travis Walters           21.01  3.50    Male     No  Sun  Dinner     3   

                    price_per_person         CC Number Payment ID  
Payer Name                                                         
Christy Cunningham              8.49  3560325168603410    Sun2959  
Douglas Tucker                  3.45  4478071379779230    Sun4608  
Travis Walters                  7.00  6011812112971322    Sun4458

In [ ]:
df.iloc[0] #integer location integer konumu #seri halinde satır bilgilerini verdi

total_bill                     16.99
tip                             1.01
sex                           Female
smoker                            No
day                              Sun
time                          Dinner
size                               2
price_per_person                8.49
CC Number           3560325168603410
Payment ID                   Sun2959
Name: Christy Cunningham, dtype: object

In [64]:
df.loc['Christy Cunningham']

total_bill                     16.99
tip                             1.01
sex                           Female
smoker                            No
day                              Sun
time                          Dinner
size                               2
price_per_person                8.49
CC Number           3560325168603410
Payment ID                   Sun2959
Name: Christy Cunningham, dtype: object

In [65]:
#birkaçtane çekmek istersek
df.head(7)

total_bill   tip     sex smoker  day    time  size  \
Payer Name                                                               
Christy Cunningham       16.99  1.01  Female     No  Sun  Dinner     2   
Douglas Tucker           10.34  1.66    Male     No  Sun  Dinner     3   
Travis Walters           21.01  3.50    Male     No  Sun  Dinner     3   
Nathaniel Harris         23.68  3.31    Male     No  Sun  Dinner     2   
Tonya Carter             24.59  3.61  Female     No  Sun  Dinner     4   
Erik Smith               25.29  4.71    Male     No  Sun  Dinner     4   
Kristopher Johnson        8.77  2.00    Male     No  Sun  Dinner     2   

                    price_per_person         CC Number Payment ID  
Payer Name                                                         
Christy Cunningham              8.49  3560325168603410    Sun2959  
Douglas Tucker                  3.45  4478071379779230    Sun4608  
Travis Walters                  7.00  6011812112971322    Sun4458  
Nathaniel Harris               11.84  4676137647685994    Sun5260  
Tonya Carter                    6.15  4832732618637221    Sun2251  
Erik Smith                      6.32   213140353657882    Sun9679  
Kristopher Johnson              4.38  2223727524230344    Sun5985

In [66]:
df.iloc[2:6] #5e kadar istedik o yüzden 6 yazdık sonuncu dahil değil;

total_bill   tip     sex smoker  day    time  size  \
Payer Name                                                             
Travis Walters         21.01  3.50    Male     No  Sun  Dinner     3   
Nathaniel Harris       23.68  3.31    Male     No  Sun  Dinner     2   
Tonya Carter           24.59  3.61  Female     No  Sun  Dinner     4   
Erik Smith             25.29  4.71    Male     No  Sun  Dinner     4   

                  price_per_person         CC Number Payment ID  
Payer Name                                                       
Travis Walters                7.00  6011812112971322    Sun4458  
Nathaniel Harris             11.84  4676137647685994    Sun5260  
Tonya Carter                  6.15  4832732618637221    Sun2251  
Erik Smith                    6.32   213140353657882    Sun9679

In [67]:
#bunu loc ile yaparız
df.loc['Travis Walters' :'Erik Smith'] #stop noktası dahil oyüzden istediğimize kadar olanı yazıyoruz sonrkaini değil

total_bill   tip     sex smoker  day    time  size  \
Payer Name                                                             
Travis Walters         21.01  3.50    Male     No  Sun  Dinner     3   
Nathaniel Harris       23.68  3.31    Male     No  Sun  Dinner     2   
Tonya Carter           24.59  3.61  Female     No  Sun  Dinner     4   
Erik Smith             25.29  4.71    Male     No  Sun  Dinner     4   

                  price_per_person         CC Number Payment ID  
Payer Name                                                       
Travis Walters                7.00  6011812112971322    Sun4458  
Nathaniel Harris             11.84  4676137647685994    Sun5260  
Tonya Carter                  6.15  4832732618637221    Sun2251  
Erik Smith                    6.32   213140353657882    Sun9679

In [ ]:
df.drop('Travis Walters') #travisi düşürdü. ama kalıcı değil kalıcı için inplace=True yapmalıydık

total_bill   tip     sex smoker   day    time  size  \
Payer Name                                                                
Christy Cunningham       16.99  1.01  Female     No   Sun  Dinner     2   
Douglas Tucker           10.34  1.66    Male     No   Sun  Dinner     3   
Nathaniel Harris         23.68  3.31    Male     No   Sun  Dinner     2   
Tonya Carter             24.59  3.61  Female     No   Sun  Dinner     4   
Erik Smith               25.29  4.71    Male     No   Sun  Dinner     4   
...                        ...   ...     ...    ...   ...     ...   ...   
Michael Avila            29.03  5.92    Male     No   Sat  Dinner     3   
Monica Sanders           27.18  2.00  Female    Yes   Sat  Dinner     2   
Keith Wong               22.67  2.00    Male    Yes   Sat  Dinner     2   
Dennis Dixon             17.82  1.75    Male     No   Sat  Dinner     2   
Michelle Hardin          18.78  3.00  Female     No  Thur  Dinner     2   

                    price_per_person         CC Number Payment ID  
Payer Name                                                         
Christy Cunningham              8.49  3560325168603410    Sun2959  
Douglas Tucker                  3.45  4478071379779230    Sun4608  
Nathaniel Harris               11.84  4676137647685994    Sun5260  
Tonya Carter                    6.15  4832732618637221    Sun2251  
Erik Smith                      6.32   213140353657882    Sun9679  
...                              ...               ...        ...  
Michael Avila                   9.68  5296068606052842    Sat2657  
Monica Sanders                 13.59  3506806155565404    Sat1766  
Keith Wong                     11.34  6011891618747196    Sat3880  
Dennis Dixon                    8.91     4375220550950      Sat17  
Michelle Hardin                 9.39  3511451626698139    Thur672  

[243 rows x 10 columns]

In [ ]:
#SORU: CC Number column unu dfin indexi yapın. Ardından 10.index ile 17.index arasındaki satırları çekin.
df.set_index('CC Number', drop = True, inplace=True ) #eğer,append=True yapsaydık CCNumber yazısını başa sütun adı gibi alacaktı

In [78]:
df.iloc[10:18]

total_bill   tip     sex smoker  day    time  size  \
CC Number                                                              
566287581219           10.27  1.71    Male     No  Sun  Dinner     2   
4577817359320969       35.26  5.00  Female     No  Sun  Dinner     4   
577040572932           15.42  1.57    Male     No  Sun  Dinner     2   
6011163105616890       18.43  3.00    Male     No  Sun  Dinner     4   
30016702287574         14.83  3.02  Female     No  Sun  Dinner     2   
180073029785069        21.58  3.92    Male     No  Sun  Dinner     2   
4240025044626033       10.33  1.67  Female     No  Sun  Dinner     3   
6521340257218708       16.29  3.71    Male     No  Sun  Dinner     3   

                  price_per_person Payment ID  
CC Number                                      
566287581219                  5.14    Sun2546  
4577817359320969              8.82    Sun6686  
577040572932                  7.71    Sun1300  
6011163105616890              4.61    Sun2971  
30016702287574                7.42    Sun3848  
180073029785069              10.79    Sun1878  
4240025044626033              3.44    Sun9715  
6521340257218708              5.43    Sun2998

# DataFrame'de Sorgu İşlemleri 

In [79]:
df=pd.DataFrame({'year':[1776,1867,1821],'pop':[328,38,126],'GDP':[20.5,1.7,1.22]} , index=['USA','CANADA','MEXICO'] )
df

year  pop    GDP
USA     1776  328  20.50
CANADA  1867   38   1.70
MEXICO  1821  126   1.22

In [82]:
#hangi ülkelerin 50milyondan fazla popülasyonu var?
df['pop']

USA       328
CANADA     38
MEXICO    126
Name: pop, dtype: int64

In [84]:
df['pop'] > 50

USA        True
CANADA    False
MEXICO     True
Name: pop, dtype: bool

In [86]:
df[df['pop'] > 50]

year  pop    GDP
USA     1776  328  20.50
MEXICO  1821  126   1.22

In [87]:
# Hangi ülkeler 1800den sonra kuruldu?
df[df['year'] > 1800]

year  pop   GDP
CANADA  1867   38  1.70
MEXICO  1821  126  1.22

In [91]:
df = pd.read_csv('tips.csv')

In [ ]:
df.head()

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15   

           Payer Name         CC Number Payment ID  
0  Christy Cunningham  3560325168603410    Sun2959  
1      Douglas Tucker  4478071379779230    Sun4608  
2      Travis Walters  6011812112971322    Sun4458  
3    Nathaniel Harris  4676137647685994    Sun5260  
4        Tonya Carter  4832732618637221    Sun2251

In [93]:
#Soru: ödenen ücreti 40dan büyük olan satırları getir 
df[df['total_bill'] > 40]

total_bill    tip     sex smoker   day    time  size  price_per_person  \
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07   
95        40.17   4.73    Male    Yes   Fri  Dinner     4             10.04   
102       44.30   2.50  Female    Yes   Sat  Dinner     3             14.77   
142       41.19   5.00    Male     No  Thur   Lunch     5              8.24   
156       48.17   5.00    Male     No   Sun  Dinner     6              8.03   
170       50.81  10.00    Male    Yes   Sat  Dinner     3             16.94   
182       45.35   3.50    Male    Yes   Sun  Dinner     3             15.12   
184       40.55   3.00    Male    Yes   Sun  Dinner     2             20.27   
197       43.11   5.00  Female    Yes  Thur   Lunch     4             10.78   
212       48.33   9.00    Male     No   Sat  Dinner     4             12.08   

          Payer Name         CC Number Payment ID  
59       Brian Ortiz  6596453823950595    Sat8139  
95     Aaron Bentley   180026611638690    Fri9628  
102    Heather Cohen   379771118886604    Sat6240  
142     Eric Andrews  4356531761046453   Thur3621  
156    Ryan Gonzales  3523151482063321    Sun7518  
170    Gregory Clark  5473850968388236    Sat1954  
182     Jose Parsons  4112207559459910    Sun2337  
184      Stephen Cox  3547798222044029    Sun5140  
197      Brooke Soto  5544902205760175   Thur9313  
212  Alex Williamson      676218815212    Sat4590

In [99]:
#Soru: cinsiyeti erk2ek olan satırları
df[df['sex'] == 'Male']

total_bill   tip   sex smoker  day    time  size  price_per_person  \
1         10.34  1.66  Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50  Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31  Male     No  Sun  Dinner     2             11.84   
5         25.29  4.71  Male     No  Sun  Dinner     4              6.32   
6          8.77  2.00  Male     No  Sun  Dinner     2              4.38   
..          ...   ...   ...    ...  ...     ...   ...               ...   
236       12.60  1.00  Male    Yes  Sat  Dinner     2              6.30   
237       32.83  1.17  Male    Yes  Sat  Dinner     2             16.42   
239       29.03  5.92  Male     No  Sat  Dinner     3              9.68   
241       22.67  2.00  Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75  Male     No  Sat  Dinner     2              8.91   

             Payer Name         CC Number Payment ID  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
5            Erik Smith   213140353657882    Sun9679  
6    Kristopher Johnson  2223727524230344    Sun5985  
..                  ...               ...        ...  
236       Matthew Myers  3543676378973965    Sat5032  
237        Thomas Brown  4284722681265508    Sat2929  
239       Michael Avila  5296068606052842    Sat2657  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  

[157 rows x 11 columns]

In [ ]:
#Cinsiyetleri kadın ve bahsis miktarı 5ten fazla olansatırlar
df[(df['sex'] == 'Female') & (df['tip'] > 5)]    #pandasta and olmaz yerine& konur. ve parantezler olmak zorunda

total_bill   tip     sex smoker   day    time  size  price_per_person  \
52        34.81  5.20  Female     No   Sun  Dinner     4              8.70   
85        34.83  5.17  Female     No  Thur   Lunch     4              8.71   
155       29.85  5.14  Female     No   Sun  Dinner     5              5.97   
214       28.17  6.50  Female    Yes   Sat  Dinner     3              9.39   

          Payer Name         CC Number Payment ID  
52      Emily Daniel  4291280793094374    Sun6165  
85       Shawna Cook  6011787464177340   Thur7972  
155   Madison Wilson  4210875236164664    Sun9176  
214  Marissa Jackson  4922302538691962    Sat3374

In [104]:
#Soru günü pazar olan ve ödenen miktar da 30dan fazla olsun
df[(df['day'] == 'Sun') & (df['total_bill'] > 30)]

total_bill   tip     sex smoker  day    time  size  price_per_person  \
11        35.26  5.00  Female     No  Sun  Dinner     4              8.82   
44        30.40  5.60    Male     No  Sun  Dinner     4              7.60   
47        32.40  6.00    Male     No  Sun  Dinner     4              8.10   
52        34.81  5.20  Female     No  Sun  Dinner     4              8.70   
112       38.07  4.00    Male     No  Sun  Dinner     3             12.69   
156       48.17  5.00    Male     No  Sun  Dinner     6              8.03   
167       31.71  4.50    Male     No  Sun  Dinner     4              7.93   
173       31.85  3.18    Male    Yes  Sun  Dinner     2             15.92   
175       32.90  3.11    Male    Yes  Sun  Dinner     2             16.45   
179       34.63  3.55    Male    Yes  Sun  Dinner     2             17.32   
180       34.65  3.68    Male    Yes  Sun  Dinner     4              8.66   
182       45.35  3.50    Male    Yes  Sun  Dinner     3             15.12   
184       40.55  3.00    Male    Yes  Sun  Dinner     2             20.27   
187       30.46  2.00    Male    Yes  Sun  Dinner     5              6.09   

           Payer Name         CC Number Payment ID  
11       Diane Macias  4577817359320969    Sun6686  
44        Todd Cooper      503846761263    Sun2274  
47       James Barnes  3552002592874186    Sun9677  
52       Emily Daniel  4291280793094374    Sun6165  
112        Jeff Lopez  3572865915176463     Sun591  
156     Ryan Gonzales  3523151482063321    Sun7518  
167    Michael Lawson  3566285921227119    Sun3719  
173       Scott Perez  3577115550328507    Sun9335  
175   Nathan Reynolds   370307040837149    Sun5109  
179      Brian Bailey   346656312114848    Sun9851  
180  James Hebert DDS      676168737648    Sun7544  
182      Jose Parsons  4112207559459910    Sun2337  
184       Stephen Cox  3547798222044029    Sun5140  
187     David Barrett  4792882899700988    Sun9987

In [ ]:
#Cumartesi veya pazar günü olan satırları getirin  | veya işareti
df[(df['day'] == 'Sat') | (df['day'] == 'Sun')]

total_bill   tip     sex smoker  day    time  size  price_per_person  \
0         16.99  1.01  Female     No  Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No  Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No  Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No  Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No  Sun  Dinner     4              6.15   
..          ...   ...     ...    ...  ...     ...   ...               ...   
238       35.83  4.67  Female     No  Sat  Dinner     3             11.94   
239       29.03  5.92    Male     No  Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes  Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes  Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No  Sat  Dinner     2              8.91   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
238      Kimberly Crane      676184013727    Sat9777  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  

[163 rows x 11 columns]

**.isin metodu** 

In [ ]:
#cumartesi pazar pazartesi getirsin 
#tek tek yazmk yerine .isin ile yaparız -içinde mi???
df[df['day'].isin(['Sun','Sat','Thur'])] #tek df içinde yazınca True False gelir iki df ile yazdık   

total_bill   tip     sex smoker   day    time  size  price_per_person  \
0         16.99  1.01  Female     No   Sun  Dinner     2              8.49   
1         10.34  1.66    Male     No   Sun  Dinner     3              3.45   
2         21.01  3.50    Male     No   Sun  Dinner     3              7.00   
3         23.68  3.31    Male     No   Sun  Dinner     2             11.84   
4         24.59  3.61  Female     No   Sun  Dinner     4              6.15   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

             Payer Name         CC Number Payment ID  
0    Christy Cunningham  3560325168603410    Sun2959  
1        Douglas Tucker  4478071379779230    Sun4608  
2        Travis Walters  6011812112971322    Sun4458  
3      Nathaniel Harris  4676137647685994    Sun5260  
4          Tonya Carter  4832732618637221    Sun2251  
..                  ...               ...        ...  
239       Michael Avila  5296068606052842    Sat2657  
240      Monica Sanders  3506806155565404    Sat1766  
241          Keith Wong  6011891618747196    Sat3880  
242        Dennis Dixon     4375220550950      Sat17  
243     Michelle Hardin  3511451626698139    Thur672  

[225 rows x 11 columns]

**..dışında olanları nasıl isteriz?**  

In [112]:
#sun dısındakiler
df[df['day'] != 'Sun']

total_bill   tip     sex smoker   day    time  size  price_per_person  \
19        20.65  3.35    Male     No   Sat  Dinner     3              6.88   
20        17.92  4.08    Male     No   Sat  Dinner     2              8.96   
21        20.29  2.75  Female     No   Sat  Dinner     2             10.14   
22        15.77  2.23  Female     No   Sat  Dinner     2              7.88   
23        39.42  7.58    Male     No   Sat  Dinner     4              9.86   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

          Payer Name         CC Number Payment ID  
19     Timothy Oneal  6568069240986485    Sat9213  
20       Thomas Rice  4403296224639756    Sat1709  
21   Natalie Gardner  5448125351489749    Sat9618  
22    Ashley Shelton  3524119516293213    Sat9786  
23    Lance Peterson  3542584061609808     Sat239  
..               ...               ...        ...  
239    Michael Avila  5296068606052842    Sat2657  
240   Monica Sanders  3506806155565404    Sat1766  
241       Keith Wong  6011891618747196    Sat3880  
242     Dennis Dixon     4375220550950      Sat17  
243  Michelle Hardin  3511451626698139    Thur672  

[168 rows x 11 columns]

In [ ]:
df[~(df['day'] == 'Sun')]  # ~ işareti de değil gibi kullanılıyor.


total_bill   tip     sex smoker   day    time  size  price_per_person  \
19        20.65  3.35    Male     No   Sat  Dinner     3              6.88   
20        17.92  4.08    Male     No   Sat  Dinner     2              8.96   
21        20.29  2.75  Female     No   Sat  Dinner     2             10.14   
22        15.77  2.23  Female     No   Sat  Dinner     2              7.88   
23        39.42  7.58    Male     No   Sat  Dinner     4              9.86   
..          ...   ...     ...    ...   ...     ...   ...               ...   
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68   
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34   
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91   
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39   

          Payer Name         CC Number Payment ID  
19     Timothy Oneal  6568069240986485    Sat9213  
20       Thomas Rice  4403296224639756    Sat1709  
21   Natalie Gardner  5448125351489749    Sat9618  
22    Ashley Shelton  3524119516293213    Sat9786  
23    Lance Peterson  3542584061609808     Sat239  
..               ...               ...        ...  
239    Michael Avila  5296068606052842    Sat2657  
240   Monica Sanders  3506806155565404    Sat1766  
241       Keith Wong  6011891618747196    Sat3880  
242     Dennis Dixon     4375220550950      Sat17  
243  Michelle Hardin  3511451626698139    Thur672  

[168 rows x 11 columns]